-- Beat — initial schema
-- Source of truth: docs/03-data-model.md
-- Migrations are forward-only. Do not edit this file after merge — write a new V###__*.sql.

-- Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ==================== USERS & WORKSPACES ====================

CREATE TABLE workspaces (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    slug            TEXT NOT NULL UNIQUE,
    logo_url        TEXT,
    primary_color   TEXT,
    plan            TEXT NOT NULL DEFAULT 'trial' CHECK (plan IN ('trial','solo','agency','enterprise')),
    plan_limit_clients         INT NOT NULL DEFAULT 5,
    plan_limit_reports_monthly INT NOT NULL DEFAULT 50,
    stripe_customer_id     TEXT,
    stripe_subscription_id TEXT,
    trial_ends_at   TIMESTAMPTZ,
    default_template_id    UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email           CITEXT NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    name            TEXT NOT NULL,
    email_verified_at TIMESTAMPTZ,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE workspace_members (
    workspace_id    UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('owner','member','viewer')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, user_id)
);

CREATE INDEX idx_workspace_members_user ON workspace_members(user_id);

CREATE TABLE sessions (
    token_hash      TEXT PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_agent      TEXT,
    ip              INET
);

CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);

-- ==================== CLIENTS ====================

CREATE TABLE clients (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    logo_url        TEXT,
    primary_color   TEXT,
    notes           TEXT,
    default_cadence TEXT CHECK (default_cadence IN ('weekly','biweekly','monthly','quarterly')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX idx_clients_workspace ON clients(workspace_id) WHERE deleted_at IS NULL;

-- ==================== OUTLETS & AUTHORS (global) ====================

CREATE TABLE outlets (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    domain          TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    tier            INT NOT NULL DEFAULT 3 CHECK (tier IN (1,2,3)),
    tier_source     TEXT NOT NULL DEFAULT 'default' CHECK (tier_source IN ('curated','llm','default','manual')),
    domain_authority INT,
    domain_authority_updated_at TIMESTAMPTZ,
    estimated_monthly_visits BIGINT,
    country         TEXT,
    language        TEXT NOT NULL DEFAULT 'en',
    last_verified_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_outlets_name_trgm ON outlets USING gin (name gin_trgm_ops);

CREATE TABLE authors (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    primary_outlet_id UUID REFERENCES outlets(id) ON DELETE SET NULL,
    email           CITEXT,
    social_handles  JSONB NOT NULL DEFAULT '{}'::jsonb,
    beat_tags       TEXT[] NOT NULL DEFAULT '{}',
    last_seen_byline_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (name, primary_outlet_id)
);

CREATE INDEX idx_authors_name_trgm ON authors USING gin (name gin_trgm_ops);
CREATE INDEX idx_authors_outlet ON authors(primary_outlet_id);

-- ==================== REPORT TEMPLATES ====================

CREATE TABLE report_templates (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID REFERENCES workspaces(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    structure       JSONB NOT NULL,
    preview_image_url TEXT,
    is_system       BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX idx_templates_workspace ON report_templates(workspace_id);

ALTER TABLE workspaces
  ADD CONSTRAINT fk_workspace_default_template
  FOREIGN KEY (default_template_id) REFERENCES report_templates(id) ON DELETE SET NULL;

-- ==================== REPORTS ====================

CREATE TABLE reports (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id       UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    workspace_id    UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    template_id     UUID NOT NULL REFERENCES report_templates(id) ON DELETE RESTRICT,
    title           TEXT NOT NULL,
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    status          TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','processing','ready','failed')),
    executive_summary TEXT,
    executive_summary_edited BOOLEAN NOT NULL DEFAULT false,
    pdf_url         TEXT,
    share_token     TEXT UNIQUE,
    share_token_expires_at TIMESTAMPTZ,
    generated_at    TIMESTAMPTZ,
    failure_reason  TEXT,
    created_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CHECK (period_end >= period_start)
);

CREATE INDEX idx_reports_client_period ON reports(client_id, period_end DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_reports_workspace_status ON reports(workspace_id, status);
CREATE INDEX idx_reports_share_token ON reports(share_token) WHERE share_token IS NOT NULL;

-- ==================== COVERAGE ITEMS ====================

CREATE TABLE coverage_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id       UUID NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    source_url      TEXT NOT NULL,
    outlet_id       UUID REFERENCES outlets(id) ON DELETE SET NULL,
    author_id       UUID REFERENCES authors(id) ON DELETE SET NULL,
    headline        TEXT,
    subheadline     TEXT,
    publish_date    DATE,
    lede            TEXT,
    summary         TEXT,
    key_quote       TEXT,
    sentiment       TEXT CHECK (sentiment IN ('positive','neutral','negative','mixed')),
    sentiment_rationale TEXT,
    subject_prominence TEXT CHECK (subject_prominence IN ('feature','mention','passing')),
    topics          TEXT[] NOT NULL DEFAULT '{}',
    estimated_reach BIGINT,
    tier_at_extraction INT,
    screenshot_url  TEXT,
    extraction_status TEXT NOT NULL DEFAULT 'queued' CHECK (extraction_status IN ('queued','running','done','failed')),
    extraction_error TEXT,
    extraction_prompt_version TEXT,
    raw_extracted   JSONB,
    is_user_edited  BOOLEAN NOT NULL DEFAULT false,
    edited_fields   TEXT[] NOT NULL DEFAULT '{}',
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_coverage_report_date ON coverage_items(report_id, publish_date DESC);
CREATE INDEX idx_coverage_outlet ON coverage_items(outlet_id);
CREATE INDEX idx_coverage_author ON coverage_items(author_id);
CREATE UNIQUE INDEX idx_coverage_report_url ON coverage_items(report_id, source_url);

-- ==================== EXTRACTION JOBS ====================

CREATE TABLE extraction_jobs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    coverage_item_id UUID NOT NULL UNIQUE REFERENCES coverage_items(id) ON DELETE CASCADE,
    status          TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','done','failed')),
    attempt_count   INT NOT NULL DEFAULT 0,
    last_error      TEXT,
    queued_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_extraction_jobs_queued ON extraction_jobs(created_at) WHERE status = 'queued';
CREATE INDEX idx_extraction_jobs_running ON extraction_jobs(started_at) WHERE status = 'running';

-- ==================== AUDIT EVENTS ====================

CREATE TABLE audit_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id    UUID REFERENCES workspaces(id) ON DELETE SET NULL,
    user_id         UUID REFERENCES users(id) ON DELETE SET NULL,
    action          TEXT NOT NULL,
    target_type     TEXT,
    target_id       UUID,
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip              INET,
    user_agent      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_workspace_time ON audit_events(workspace_id, created_at DESC);

-- ==================== TRIGGERS: updated_at ====================

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t TEXT;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.columns
             WHERE column_name = 'updated_at' AND table_schema = 'public'
    LOOP
        EXECUTE format(
            'CREATE TRIGGER trg_%s_updated_at BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION set_updated_at()', t, t);
    END LOOP;
END $$;
