server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location ~* \.(?:js|css|svg|woff2?|png|jpg|jpeg|gif)$ {
    expires 7d;
    add_header Cache-Control "public, max-age=604800, immutable";
  }
}
