app = "beat-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  API_PORT = "8080"
  SPRING_PROFILES_ACTIVE = "prod"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 2

  [http_service.checks]
    [[http_service.checks.http]]
      method = "GET"
      path = "/v1/healthz"
      interval = "15s"
      timeout = "2s"
      grace_period = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory = "2gb"
